In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print (torch.__version__)

2.3.0+cpu


In [3]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
# how many dimensions

scalar.ndim

0

In [5]:
# Get tensor back as python int

scalar.item()

7

In [9]:
# Vector

vector = torch.tensor([2,5])

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [13]:
# MATRIX

MATRIX = torch.tensor([[7,2],[6,2]])

In [14]:
MATRIX

tensor([[7, 2],
        [6, 2]])

In [15]:
MATRIX.ndim

2

In [19]:
MATRIX[0]

tensor([7, 2])

In [20]:
MATRIX.shape

torch.Size([2, 2])

In [21]:
# TENSOR

TENSOR = torch.tensor([[[1,2,5],[5,2,4],[8,7,3]]])

In [22]:
TENSOR

tensor([[[1, 2, 5],
         [5, 2, 4],
         [8, 7, 3]]])

In [23]:
TENSOR.ndim

3

In [24]:
TENSOR.shape

torch.Size([1, 3, 3])

In [25]:
TENSOR[0]

tensor([[1, 2, 5],
        [5, 2, 4],
        [8, 7, 3]])

Lesson 2 Random Tenosrs


In [38]:
random_tensor = torch.rand(1,3,4)

In [39]:
random_tensor

tensor([[[0.1912, 0.4252, 0.8433, 0.2298],
         [0.0805, 0.8372, 0.9152, 0.9314],
         [0.4609, 0.2619, 0.3620, 0.3916]]])

In [40]:
# random image tensor

random_image_tensor = torch.rand(size = (224, 224, 3)) # height, width, colour pallete red green blue
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [41]:
# Zeros and ones tensors

zeros = torch.torch.zeros(size = (3,4))
zeros

zeros * random_tensor



tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [42]:
ones = torch.torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [43]:
ones.dtype

torch.float32

Lesson 3 {1:49}

Creating a range of tensors and tensors-like

In [53]:
# using torch.range()

range_tensor = torch.arange(start =1, end = 32, step = 3)
range_tensor

tensor([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31])

In [58]:
# creating tensors like

ten_zeros = torch.zeros_like(input = range_tensor)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Lessons 4 Tensor Datatypes {1:54}

{research precision in computing to understan 16 32 64 etc}

In [65]:
# Float 32 tensor

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = torch.float16)

print(float_32_tensor)
print(float_32_tensor.dtype)

tensor([3., 6., 9.], dtype=torch.float16)
torch.float16


In [73]:
# Float 32 tensor

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # What datatype is the tensor
                               device= None, # cpu or gpu{Dont have cuda installed}
                               requires_grad= False) # track gradietns

print(float_32_tensor)
print(float_32_tensor.dtype)

tensor([3., 6., 9.])
torch.float32


In [75]:
# Float 16 tensor 

float_16_tensor = float_32_tensor.type(torch.float16)

print(float_16_tensor)
print(float_16_tensor.dtype)

tensor([3., 6., 9.], dtype=torch.float16)
torch.float16


In [78]:
multiply_tensor = float_16_tensor * float_32_tensor

In [79]:
multiply_tensor.dtype

torch.float32

Getting information from tensors

1. Tensors not right datatype - tensor.dtype
2. Tensors not right shape - tensor.shape
3. Tensors not on the right device - tensor.device

In [80]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.0717, 0.8365, 0.3685, 0.9292],
        [0.3598, 0.6871, 0.6674, 0.1880],
        [0.5524, 0.0741, 0.8141, 0.8889]])

In [88]:
# find out details about some tensor attributes
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.0717, 0.8365, 0.3685, 0.9292],
        [0.3598, 0.6871, 0.6674, 0.1880],
        [0.5524, 0.0741, 0.8141, 0.8889]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Lesson 5/6 Manipulating Tensors {2:12}

Usual 4 opertations {elementwie multiplication} but also can do matrix multiplication

In [89]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [90]:
# Create a tensor and multiply 10 by it
tensor * 10

tensor([10, 20, 30])

In [91]:
# Create a tensor and subtract 10
tensor - 10

tensor([-9, -8, -7])

In [92]:
# Create a tensor and divide by 10
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [95]:
# Pytorch built in functions

print(torch.mul(tensor, 10))
print(torch.add(tensor, 10))
print(torch.sub(tensor, 10))
print(torch.div(tensor, 10))

tensor([10, 20, 30])
tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([0.1000, 0.2000, 0.3000])


In [96]:
tensor

tensor([1, 2, 3])

In [97]:
# Elemental Multiplication

tensor * tensor

tensor([1, 4, 9])

In [98]:
# Matrix Multiplication

torch.matmul(tensor,tensor)

tensor(14)

In [99]:
%%time
value = 0
for i in range (len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: total: 0 ns
Wall time: 20 ms


tensor(14)

In [100]:
%%time
torch.matmul(tensor,tensor)

CPU times: total: 0 ns
Wall time: 1 ms


tensor(14)